export const dynamic = 'force-dynamic'

import { db } from '@/lib/db'
import { aiIdeas } from '@/lib/db/schema'
import { eq, and } from 'drizzle-orm'
import { IdeaCard } from '@/components/ideas/IdeaCard'
import { IdeaFilters } from '@/components/ideas/IdeaFilters'
import { IdeaGenerateButton } from '@/components/ideas/IdeaGenerateButton'

interface Props {
  searchParams: Promise<{
    status?: string
    assetClass?: string
    signalType?: string
    riskLevel?: string
  }>
}

export default async function IdeasPage({ searchParams }: Props) {
  const sp = await searchParams
  const filters = []

  if (sp.status) filters.push(eq(aiIdeas.status, sp.status as 'pending' | 'approved' | 'dismissed'))
  if (sp.assetClass) filters.push(eq(aiIdeas.assetClass, sp.assetClass as 'stock' | 'etf' | 'bond' | 'commodity' | 'portfolio'))
  if (sp.signalType) filters.push(eq(aiIdeas.signalType, sp.signalType as 'buy' | 'sell' | 'hold' | 'rebalance' | 'risk_flag' | 'news'))
  if (sp.riskLevel) filters.push(eq(aiIdeas.riskLevel, sp.riskLevel as 'low' | 'medium' | 'high'))

  const ideas = await db
    .select()
    .from(aiIdeas)
    .where(filters.length ? and(...filters) : undefined)
    .orderBy(aiIdeas.generatedAt)
    .then((rows) => rows.reverse())

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-zinc-900">AI Ideas</h1>
          <p className="text-sm text-zinc-600 mt-1">
            Investment signals generated by Claude — approve or dismiss each one.
          </p>
        </div>
        <IdeaGenerateButton />
      </div>

      <div className="bg-white rounded-xl border border-zinc-200 px-5 py-4">
        <IdeaFilters />
      </div>

      {ideas.length === 0 ? (
        <div className="text-center py-16 text-zinc-600">
          <p className="text-lg">No ideas yet.</p>
          <p className="text-sm mt-1">Click &ldquo;Generate Ideas&rdquo; to let Claude analyze your portfolio.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {ideas.map((idea) => (
            <IdeaCard key={idea.id} idea={idea} />
          ))}
        </div>
      )}
    </div>
  )
}
